#!/usr/bin/env bash
# File: pre_install_prep.sh
#
# Purpose:
#   - Run once, BEFORE reboot.
#   - Updates OS, installs prereqs, enables interfaces (SSH/I2C/SPI), sets groups.
#   - Creates the "after reboot" script and tells you exactly what to do next.
#
# Usage:
#   sudo bash pre_install_prep.sh
#
set -euo pipefail

# Detect the real user (who ran sudo, or current if root/direct)
TARGET_USER="${SUDO_USER:-${USER}}"
# If running as root without sudo (e.g. direct root login), warn/fallback
if [[ "${TARGET_USER}" == "root" ]]; then
    # try to find a non-root user? or just warn.
    # For Pi standard, usually 'pi' or the first user (uid 1000).
    # We'll just stick with what we found but valid non-root is better.
    echo "WARN: Detected target user is 'root'. Ideally run this via 'sudo' from your normal user account."
fi

# Get the primary group of that user
TARGET_GROUP="$(id -gn "${TARGET_USER}")"

REPO_SSH="git@github.com:benczech212/pi_magic_8ball.git"
INSTALL_DIR="/opt/pi_magic_8ball"
POST_SCRIPT="/home/${TARGET_USER}/02_pi_magic8_post_reboot.sh"

log() { echo -e "\n=== $* ==="; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: run as root: sudo bash $0"
    exit 1
  fi
}

user_exists() {
  id "${TARGET_USER}" >/dev/null 2>&1
}

enable_interfaces_noninteractive() {
  # Uses raspi-config nonint when available (Pi OS)
  # Enables: ssh, i2c, spi
  if command -v raspi-config >/dev/null 2>&1; then
    raspi-config nonint do_ssh 0 || true
    raspi-config nonint do_i2c 0 || true
    raspi-config nonint do_spi 0 || true
  else
    echo "WARN: raspi-config not found. Skipping interface enable step."
  fi
}

install_packages() {
  log "Updating OS and installing packages"
  apt update
  apt -y full-upgrade

  apt install -y \
    git \
    python3 python3-pip python3-venv python3-dev \
    build-essential \
    i2c-tools \
    python3-rpi.gpio \
    python3-gpiozero \
    python3-pil \
    python3-pygame \
    fonts-dejavu \
    fonts-freefont-ttf \
    python3-tk
}

ensure_groups() {
  log "Adding ${TARGET_USER} to gpio/i2c/spi groups (for later hardware IO)"
  usermod -aG gpio,i2c,spi "${TARGET_USER}" || true
}

write_post_reboot_script() {
  log "Writing post-reboot setup script to: ${POST_SCRIPT}"

  # 1. Write the header with EXPANDED variables from this script
  cat > "${POST_SCRIPT}" <<EOF
#!/usr/bin/env bash
# File: 02_pi_magic8_post_reboot.sh
# Generated by pre_install_prep.sh on $(date)

set -euo pipefail

# --- Configuration (Injected from pre-install) ---
TARGET_USER="${TARGET_USER}"
TARGET_GROUP="${TARGET_GROUP}"
REPO_SSH="${REPO_SSH}"
INSTALL_DIR="${INSTALL_DIR}"
# -------------------------------------------------

EOF

  # 2. Append the rest of the script logic WITHOUT expansion (quoted heredoc)
  #    This preserves \$variables inside the logical code.
  cat >> "${POST_SCRIPT}" <<'EOF'

log() { echo -e "\n=== $* ==="; }

require_user() {
  if [[ "$(whoami)" != "${TARGET_USER}" ]]; then
    echo "ERROR: run as ${TARGET_USER}. Try: sudo su - ${TARGET_USER}"
    exit 1
  fi
}

ensure_ssh_key() {
  log "Ensuring GitHub SSH key exists for ${TARGET_USER}"
  mkdir -p "${HOME}/.ssh"
  chmod 700 "${HOME}/.ssh"

  if [[ ! -f "${HOME}/.ssh/id_ed25519" ]]; then
    ssh-keygen -t ed25519 -C "${TARGET_USER}-pi-magic8" -f "${HOME}/.ssh/id_ed25519" -N ""
  fi

  chmod 600 "${HOME}/.ssh/id_ed25519"
  chmod 644 "${HOME}/.ssh/id_ed25519.pub"

  log "Your GitHub SSH public key (add this to GitHub > Settings > SSH keys):"
  echo "------------------------------------------------------------"
  cat "${HOME}/.ssh/id_ed25519.pub"
  echo "------------------------------------------------------------"
  echo
  echo "After adding the key, test with:"
  echo "  ssh -T git@github.com"
}

prep_opt_dir() {
  log "Preparing /opt directory ownership"
  sudo mkdir -p /opt
  sudo chown -R "${TARGET_USER}:${TARGET_GROUP}" /opt
}

clone_or_update_repo() {
  log "Cloning repo into ${INSTALL_DIR}"
  if [[ -d "${INSTALL_DIR}/.git" ]]; then
    echo "Repo already exists; pulling latest..."
    cd "${INSTALL_DIR}"
    git pull
  else
    cd /opt
    git clone "${REPO_SSH}" "${INSTALL_DIR##*/}"
  fi
}

setup_venv_and_deps() {
  log "Creating Python venv and installing deps"
  cd "${INSTALL_DIR}"

  if [[ ! -d ".venv" ]]; then
    python3 -m venv .venv
  fi

  # shellcheck disable=SC1091
  source .venv/bin/activate

  python -m pip install --upgrade pip setuptools wheel

  if [[ -f requirements.txt ]]; then
    pip install -r requirements.txt
  else
    # Fallback: safe defaults for this kind of project
    pip install pillow gpiozero pyyaml pygame
  fi
}

setup_desktop_autostart() {
  log "Setting up Desktop Shortcut and Autostart"

  # Ensure directories exist
  mkdir -p "${HOME}/Desktop"
  mkdir -p "${HOME}/.config/autostart"

  # Path for the Main .desktop file
  local desktop_file="${HOME}/Desktop/Magic8Ball.desktop"
  # Path for the Config .desktop file
  local config_desktop_file="${HOME}/Desktop/Magic8Ball_Config.desktop"

  log "Creating ${desktop_file}"

  # 1. Main App Shortcut
  cat > "${desktop_file}" <<DESKTOP_EOF
[Desktop Entry]
Type=Application
Name=Magic 8 Ball
Comment=Pi Magic 8 Ball
Exec=${INSTALL_DIR}/.venv/bin/python -m src.main
Path=${INSTALL_DIR}
Icon=utilities-terminal
Terminal=false
Categories=Utility;
DESKTOP_EOF

  # 2. Config App Shortcut
  log "Creating ${config_desktop_file}"
  cat > "${config_desktop_file}" <<DESKTOP_2_EOF
[Desktop Entry]
Type=Application
Name=Magic 8 Ball Config
Comment=Configure Magic 8 Ball
Exec=${INSTALL_DIR}/.venv/bin/python -m src.main --configure
Path=${INSTALL_DIR}
Icon=preferences-system
Terminal=false
Categories=Utility;Settings;
DESKTOP_2_EOF

  # 3. Update App Shortcut
  update_desktop_file="${DESKTOP_DIR}/Update Magic 8 Ball.desktop"
  log "Creating ${update_desktop_file}"
  cat > "${update_desktop_file}" <<DESKTOP_3_EOF
[Desktop Entry]
Type=Application
Name=Update Magic 8 Ball
Comment=Git Pull and Restart
Exec=${INSTALL_DIR}/scripts/update.sh
Path=${INSTALL_DIR}
Icon=system-software-update
Terminal=true
Categories=Utility;System;
DESKTOP_3_EOF

  # Make them executable
  chmod +x "${desktop_file}"
  chmod +x "${config_desktop_file}"
  chmod +x "${update_desktop_file}"

  # Copy MAIN app to autostart (only the main app)
  log "Enabling Autostart for Main App"
  cp "${desktop_file}" "${HOME}/.config/autostart/"

  echo "Desktop shortcuts created. Main app added to Autostart."
}

main() {
  # require_user
  ensure_ssh_key

  echo
  echo "IMPORTANT: If you just created/changed SSH keys, add it to GitHub NOW,"
  echo "then run:  ssh -T git@github.com"
  echo "If that succeeds, continue."
  echo

  prep_opt_dir
  clone_or_update_repo
  setup_venv_and_deps
  setup_desktop_autostart

  log "Done"
}

main "$@"
EOF

  chown "${TARGET_USER}:${TARGET_GROUP}" "${POST_SCRIPT}"
  chmod +x "${POST_SCRIPT}"
}

main() {
  require_root

  if ! user_exists; then
    echo "ERROR: user '${TARGET_USER}' does not exist on this Pi."
    echo "Create it first (or edit TARGET_USER in this script)."
    exit 1
  fi

  install_packages

  log "Enabling interfaces (ssh/i2c/spi)"
  enable_interfaces_noninteractive

  ensure_groups
  write_post_reboot_script

  log "Next steps"
  echo "1) Reboot now:"
  echo "   sudo reboot"
  echo
  echo "2) After reboot, run as ${TARGET_USER}:"
  echo "   bash ${POST_SCRIPT}"
}

main "$@"
